"""add audit_agent tables

Revision ID: 546422ce6f2a
Revises: e773abb84b4a
Create Date: 2026-08-23 17:57:49.212116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546422ce6f2a'
down_revision: Union[str, Sequence[str], None] = 'e773abb84b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_runs_requested_by'), ['requested_by'], unique=False)

    op.create_table('audit_memory_snapshots',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('document_summary', sa.Text(), nullable=False),
    sa.Column('map_batches_used', sa.Integer(), nullable=False),
    sa.Column('memory_after', sa.JSON(), nullable=False),
    sa.Column('memory_compacted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_memory_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_memory_snapshots_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_memory_snapshots_run_id'), ['run_id'], unique=False)

    op.create_table('audit_reports',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('risk_summary', sa.JSON(), nullable=False),
    sa.Column('documents_covered', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_reports_run_id'), ['run_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_reports_run_id'))

    op.drop_table('audit_reports')
    with op.batch_alter_table('audit_memory_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_memory_snapshots_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_memory_snapshots_document_id'))

    op.drop_table('audit_memory_snapshots')
    with op.batch_alter_table('audit_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_runs_requested_by'))

    op.drop_table('audit_runs')
    # ### end Alembic commands ###
